// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzRY7fQnHMzo6K5M_ERK0uZ2bcsZ80-Qg',
    appId: '1:935896752888:android:f4524f8bf8a8d0737fd10d',
    messagingSenderId: '935896752888',
    projectId: 'myrecipe-e33c5',
    storageBucket: 'myrecipe-e33c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmufzIGT4kbfrhtPCoMLOOplU1c43cMfc',
    appId: '1:935896752888:ios:08bb484a92e2aa5a7fd10d',
    messagingSenderId: '935896752888',
    projectId: 'myrecipe-e33c5',
    storageBucket: 'myrecipe-e33c5.firebasestorage.app',
    androidClientId: '935896752888-t2f37220vktah8og0ni0nc9sd208pa1v.apps.googleusercontent.com',
    iosClientId: '935896752888-1ldsprhcag4nu39nejrb9aipo3u1il18.apps.googleusercontent.com',
    iosBundleId: 'com.example.myRecipe',
  );

}